openapi: 3.0.1

info:
  title: CodeScuffle Code Running API
  description: 'Run CodeScuffle solutions'
  license:
    name: MIT license
    url: https://github.com/Andriamanitra/codescuffle/blob/main/LICENSE
  version: 0.0.1

servers:
- url: http://localhost:8080/api/v1/

tags:
- name: code
  description: Running code
- name: languages
  description: Information about available languages

paths:
  /run/{language}:
    post:
      tags:
      - code
      summary: Run some code written in a specific language and return the output
      operationId: runCode
      parameters:
      - name: language
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/LanguageName'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeRunRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeRunResult'
        400:
          description: Invalid request
        404:
          description: Specified language not found or supported

  /execute:
    post:
      tags:
      - code
      summary: "(NOT IMPLEMENTED YET) Run some code written in a specific language"
      description: "This end point is similar to the one provided by [Piston](https://github.com/engineer-man/piston/pkgs/container/piston) code execution engine"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
        400:
          description: Invalid request
        500:
          description: Internal server error

  /languages:
    get:
      tags:
      - languages
      summary: Get a list of supported languages
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'

components:
  schemas:
    LanguageName:
      type: string
      enum:
      - crystal
      - julia
      - ruby

    CodeRunRequest:
      type: object
      description: Object describing the code to run. In the future this object may also specify other requirements (environment variables or files that need to be created before execution, compilation flags, time/memory limits... )
      properties:
        code:
          type: string
        stdin:
          type: string
      example:
        code: print(readline())
        stdin: "Hello world!"

    CodeRunResult:
      type: object
      properties:
        stdout:
          type: string
        stderr:
          type: string
        compilation_stdout:
          type: string
        compilation_stderr:
          type: string
        compilation_time:
          type: number
          description: If a language is compiled, time taken to compile the code (in seconds), otherwise 0
        execution_time:
          type: number
          description: Time taken to run the code (in seconds)
      example:
        stdout: Hello World!
        stderr: ''
        compilation_stdout: ''
        compilation_stderr: ''
        compilationTime: 0.0
        executionTime: 0.105815

    Language:
      type: object
      properties:
        language:
          $ref: '#/components/schemas/LanguageName'
        version:
          type: string
      example:
        language: julia
        version: 1.6.2

    File:
      type: object
      required:
      - content
      properties:
        name:
          type: string
        content:
          type: string

    ExecuteRequest:
      type: object
      required:
      - language
      - version
      - files
      properties:
        language:
          type: string
        version:
          description: "The version of the language to use for execution, must be a string containing a SemVer selector for the version or the specific version number to use."
          type: string
        files:
          description: "An array of files containing code or other data that should be used for execution. The first file in this array is considered the main file."
          type: array
          items:
            $ref: '#/components/schemas/File'
        stdin:
          type: string
          default: ''
        args:
          type: array
          items:
            type: string
          default: []
        compile_timeout:
          type: number
          default: 10000
        run_timeout:
          type: number
          default: 3000
        compile_memory_limit:
          type: number
          default: -1
        run_memory_limit:
          type: number
          default: -1

    ExecutionResult:
      type: object
      required:
      - language
      - run
      properties:
        language:
          type: string
          example: julia
        version:
          type: string
          example: 1.6.2
        run:
          type: object
          required:
          - stdout
          - stderr
          properties:
            stdout:
              type: string
              example: Hello world!
            stderr:
              type: string
              example: ''
