version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      # TODO: read these from environment variables or something
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
